#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

HOME_DIR=$(echo ~)
DIR=./${DIR#"$HOME_DIR/"}

cd ~
ln -sf $DIR/.bash
ln -sf $DIR/.vim
ln -sf $DIR/.profile
ln -sf $DIR/.vimrc

source .profile

cd $DIR

git submodule init
git submodule update

echo "All done, enjoy!"
