#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

HOME_DIR=$(echo ~)
DIR=./${DIR#"$HOME_DIR/"}

cd $HOME_DIR

mkdir .envbackup 2>/dev/null
mv .bash .envbackup/ 2>/dev/null
mv .vim .envbackup/ 2>/dev/null
mv .vimrc .envbackup/ 2>/dev/null
mv .profile .envbackup/ 2>/dev/null
mv .bashrc .envbackup/ 2>/dev/null
mv .nvmstuff .envbackup/ 2>/dev/null

ln -sf $DIR/.bash
ln -sf $DIR/.vim
ln -sf $DIR/.profile
ln -sf $DIR/.bashrc
ln -sf $DIR/.vimrc
ln -sf $DIR/.nvmstuff

source .profile

cd $DIR

git submodule init
git submodule update

echo "All done, enjoy!"
