#!/bin/bash

cd ~

# only uninstall if we have a backup or have been actually installed
if [[ -d .envbackup ]]; then

  # remove everything we created
  rm .bash 2>/dev/null
  rm .vim 2>/dev/null
  rm .profile 2>/dev/null
  rm .bashrc 2>/dev/null
  rm .vimrc 2>/dev/null
  rm .nvmstuff 2>/dev/null

  # Move anything we saved
  mv .envbackup/* ./ 2>/dev/null

  # remove our backup
  rm -r .envbackup
fi

if [[ -e .profile ]]; then
  source .profile
elif [[ -e .bashrc ]]; then
  source .bashrc
fi

echo "Should be as it was now"
