#!/bin/bash

project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
home_dir=$(echo ~)

if ! [ -d $project_dir ]; then 
	echo "Unable to locate project directory $project_dir"
	exit 1
fi

for file in $(ls -A $project_dir)
do

  if ! [[ $FILE == ".git" || $FILE == ".gitmodules" || $FILE =~ ".bak" ||$FILE =~ ".md" || $FILE =~ "install" || $FILE =~ ".sw" || $FILE =~ ".DS_Store" || $FILE =~ "font" || $FILE =~ ".txt" ]]; then

    # if the file exists and is not a symbolic link, if it is a symbolic link
    # then we've been here before
    if [[ -L $home_dir/$file ]]; then

      rm $home_dir/$file
    fi

  fi
done

if [ -d $project_dir/.bak ]; then 
	mv $project_dir/.bak/* $home_dir/
fi

echo "Should be returned to how you had it before..."
