#!/bin/bash

yarn version --new-version $1

# update the upstream
echo "setting upstream origin"
git branch --set-upstream-to=origin/$BRANCH_NAME $BRANCH_NAME
echo "pushing"
git push -u
git push --tags
