#!/bin/bash

rushx lint:fix 

if [ -z "$(git status --untracked-files=no --porcelain)" ]; then 
    echo "No lint:fix"
  else 
    git add -u 
    OLD_MSG=$(git log --format=%B -n1)
    git commit --amend -m "$OLD_MSG" -m "\nlint:fix"
fi
