#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Branch: $BRANCH"

if [[ $BRANCH =~ ^([A-Z]*-)?[0-9]*$ ]]; then

  MSG_FILE_PATH=$1

  # make sure it isn't there already
  MATCHES=$(head -1 $MSG_FILE_PATH | grep "$BRANCH" 2> /dev/null)

  if [[ -z $MATCHES ]]; then

    MSG_FILE_CONTENTS=$(cat $MSG_FILE_PATH)

    if [[ -z "${BASH_REMATCH[1]}" ]]; then

      # is github
      # Add github issue key to the commit
      echo "$MSG_FILE_CONTENTS #$BRANCH" > $MSG_FILE_PATH

    else

      # is bitbucket
      # Add Jira issue key to the commit
      echo "$BRANCH " > $MSG_FILE_PATH
      echo "$MSG_FILE_CONTENTS" >> $MSG_FILE_PATH

    fi

  fi
fi
